spring:
  application:
    name: greeting-service
  cloud:
    config:
      enabled: false

greeting-service:
  greeting: "Hola"
  default-value: "Mundo!"

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'